### ISSUE TITLE
Issue in matching residues 

### ISSUE THREAD

**Issue by renee9904** [delphi001/SAAMBE-3D#9]
Hi, I have tried to use this tool to predict DDG after mutation in SARS-CoV-2 spike protein and ACE2.
Based on the fasta sequence provided by PDB database (and I also checked the residues and positions in PDB file), the sequence from 1 to 10 is `MFVFLVLLPL`  in chain C. 
But when I run the command `python saambe-3d.py -i  7KNE.pdb -c C -r 2 -w F -m v -d 1`, it got error `ERROR>> Claimed wild-type residue 'F' in 'chain C and resid 2' not found.`

I am feeling quite confused about this particular issue, and I understand that it may not be due to the tool itself because the example code works well. Given my lack of experience in this field, I was wondering if there are any important details that I may have overlooked during the process. Thank you very much for your help.

**Comment by delphi001** [comment]
Hi, SAAMBE-3D being a structure-based method expects coordinate information for the residue to be mutated to present in the input PDB file. While, though the protein sequence matches the coordinates are missing. Please check your PDB 7KNE.pdb (REMARK 465 MISSING RESIDUES), check line # 151, (```REMARK 465     PHE C     2```) is among the missing residues. 

So, the ERROR message you are getting is exactly telling what the issue is. For your given example case SAAMBE-3D is not applicable. If you want to make a prediction for this mutation you may have to look for sequence-based methods. You may give SAAMBE-SEQ a try. Note: SAAMBE-SEQ works for dimers, so you can not consider all the chains but only two. One the interaction chain and the other chain in which mutation exists.

Thank you!

**Comment by renee9904** [comment]
Thank you so much for explaining everything! Now I understand and you saved my day.
